### ISSUE TITLE
Incorrect fluid packet conversion with ME Fluid Discretizer 

### ISSUE THREAD

**Issue by cpaca** [GlodBlock/AE2FluidCraft-Rework#146] opened 2024-04-04 11:35 UTC
[Version 1.12.2]

Putting a fluid packet into an AE network that has an ME Fluid Discretizer will convert the packet into 1mB of fluid.

It doesn't matter how much actual fluid was in the packet, it destroys the entire packet and only produces 1 mB.

**Comment by GlodBlock** [comment] 2024-04-04 11:47
i can't reproduce it with the latest ae2fc. please make sure you are using the latest one.
you need to show me your full modlist if it is still happening in latest version

**Comment by cpaca** [comment] 2024-04-04 15:13
(I'm reading this modlist off of the *mods* menu in Forge, cause I can't figure out how to auto-export the modlist.)
Modlist:

Minecraft 1.12.2 
Minecraft Coder Pack v9.42 (I think this is part of root mc?)
Forge Mod Loader 8.0.99.99
Minecraft Forge 14.23.5.2859
MixinBooter 8.4
AE2 Unofficial Extended Life 0.56.4
Ae2 Fluid Crafting 2.5.8-r
Shadowfacts' Forgelin 1.8.4
LibrarianLib 4.22
LibrarianLib Stage 2 4.22

I'm also attaching a screenshot of my mods folder if you want to cross-reference with that.

![Screenshot of modlist](https://github.com/AE2-UEL/AE2FluidCraft-Rework/assets/37684627/79b3165a-2833-4410-8541-b9a4e2a926a8)

I'm gonna see if I can get some other people to replicate the same issue on their machines as well - so far it seems like this is only an issue for me? but I'm not sure if I installed the same version of the mods as everyone else.

**Comment by cpaca** [comment] 2024-04-04 15:24
Got prism to export the modlist properly, here it is:

1.12.2
BD Lib (http://bdew.net/mods/) [1.14.4.1] by bdew
AE2 Fluid Crafting [2.5.8-r] by GlodBlock
memory_repo
Inventory Tweaks (https://github.com/Kobata/inventory-tweaks) [1.64+dev.151.822d839] by Jimeo Wan, Kobata
libnine [1.2.0] by phantamanta44
ConfigAnytime [1.0] by CleanroomMC
!mixinbooter-8.4
AE2 Unofficial Extended Life (https://github.com/AE2-UEL/Applied-Energistics-2) [v0.56.4] by NotMyWing, Serenibyss, PrototypeTrousers, AlgorithmX2, contributors <3
LibrarianLib [4.22] by thecodewarrior, wiresegal, LordSaad44, Elucent, Eladkay, murapix, werty1124, Leviathan143
B.A.S.E (http://minecraft.curseforge.com/projects/b-a-s-e) [1.12.2-3.13.0] by SkySom, Lanse505, Jared, EwyBoy
AE2 Stuff (http://bdew.net) [0.7.0.4] by bdew
Shadowfacts' Forgelin (https://github.com/shadowfacts/Forgelin) [1.8.4] by shadowfacts

**Comment by GlodBlock** [comment] 2024-04-04 15:53
ok, i will fix that soon

**Comment by GlodBlock** [comment] 2024-04-05 07:24
fixed in https://github.com/AE2-UEL/AE2FluidCraft-Rework/releases/tag/2.5.9-r

**Closed as completed by GlodBlock** 2024-04-05 07:24 UTC
Labels: fixed
